---
- hosts: all
  become: yes
  tasks:
    - name: Update the apt package index
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Install packages for apt add repository over HTTPS
      become: yes
      apt:
        name: "{{ packagesdep }}"
        force_apt_get: yes
        state: latest
        update_cache: yes
      vars:
        packagesdep:
        - apt-transport-https
        - ca-certificates
        - gnupg
        - curl

    - name: Add Apt signing key from official docker repo
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add docker official repository for Debian Bullseye
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
        state: present

    - name: Index new repo into the cache
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Install Containerd and Docker
      apt:
        name: "{{ packagesdep }}"
        force_apt_get: yes
        state: latest
        update_cache: yes
      vars:
        packagesdep:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

- hosts: control:worker
  become: yes
  tasks:
    - name: Add Kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes' APT repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: 'kubernetes'

    - name: Install kubelet
      apt:
        name: kubelet=1.27.1-00
        state: present
        update_cache: true

    - name: Install kubeadm
      apt:
        name: kubeadm=1.27.1-00
        state: present

    - name: Update containerd configuration
      copy:
        dest: "/etc/containerd/config.toml"
        content: |
          enabled_plugins = ["cri"]
          version = 2
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
            runtime_type = "io.containerd.runc.v2"
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
              SystemdCgroup = true

    - name: Restart containerd
      systemd:
        state: restarted
        name: containerd

- hosts: control
  become: yes
  tasks:
    - name: Install kubectl
      apt:
        name: kubectl=1.27.1-00
        state: present
        force: yes
