---
- hosts: control
  become: yes
  gather_facts: false
  tasks:
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: worker
  become: yes
  tasks:
    - name: Join the cluster
      shell: "{{ hostvars['control-1'].join_command }}"

    - name: Create flannel dir
      file: 
        path: /run/flannel
        state: directory
        mode: '0755'

    - name: Create flannel subnet file
      copy:
        src: subnet.env
        dest: /run/flannel/subnet.env
