---
- hosts: control
  become: yes
  vars:
    username: control
  tasks:
    - name: Create the user
      user: name="{{username}}" append=yes state=present createhome=yes shell=/bin/bash

    - name: Allow the user to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Set up authorized keys for the user
      authorized_key: user="{{username}}" key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: Set a hostname
      hostname:
        name: control-1
        use: systemd

- hosts: worker
  become: yes
  vars:
    username: worker
  tasks:
    - name: Create the user
      user: name="{{username}}" append=yes state=present createhome=yes shell=/bin/bash

    - name: Allow the user to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Set up authorized keys for the user
      authorized_key: user="{{username}}" key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: Set a hostname
      hostname:
        name: "{{ inventory_hostname }}"
        use: systemd
